# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  desafio1:
    image: desafio1
    build:
      context: .
      dockerfile: Desafio1/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5011:5011
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
